name: flutter_app_components
description: A new Flutter package.
version: 1.0.0
publish_to: none
homepage: "https://github.com/niwatly"

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  auto_size_text: ^3.0.0
  fluro: ^2.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_state_notifier: ^0.7.1
  freezed_annotation: ^2.2.0
  gap: ^2.0.0
  grinder: ^0.9.2
  hooks_riverpod: ^2.0.2
  http: ^0.13.5
  image: ^3.2.2
  in_app_review: ^2.0.4
  package_info: ^2.0.2
  path_provider: ^2.0.11
  provider: ^6.0.4
  rxdart: ^0.27.5
  shared_preferences: ^2.0.15
  state_notifier: ^0.7.2+1
  tutorial_coach_mark: ^1.2.4
  url_launcher: ^6.1.6
  version: ^3.0.2

dev_dependencies:
  build_runner: ^2.3.2
  dart_code_metrics: ^4.21.2
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter: null
