name: flutter_app_components
description: A new Flutter package.
version: 1.0.0
publish_to: none
homepage: "https://github.com/niwatly"

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: 3.3.4

dependencies:
  auto_size_text: ^3.0.0
  fluro: ^2.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_state_notifier: ^0.7.1
  freezed_annotation: ^2.0.3
  gap: ^2.0.0
  grinder: ^0.9.1
  hooks_riverpod: ^2.0.0-dev.9
  http: ^0.13.4
  image: ^3.1.3
  in_app_review: ^2.0.4
  package_info: ^2.0.2
  path_provider: ^2.0.10
  provider: ^6.0.2
  rxdart: ^0.27.3
  shared_preferences: ^2.0.15
  state_notifier: ^0.7.2+1
  tutorial_coach_mark: ^1.2.2
  url_launcher: ^6.1.2
  version: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.11
  dart_code_metrics: ^4.15.2
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter: null
