name: flutter_app_components
description: A new Flutter package.
version: 1.0.0
publish_to: none
homepage: "https://github.com/niwatly"

environment:
  sdk: ">=2.19.6 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  fluro: ^2.0.5
  flutter:
    sdk: flutter
  flutter_state_notifier: ^0.7.3
  freezed_annotation: ^2.2.0
  gap: ^3.0.0
  grinder: ^0.9.4
  http: ^1.1.0
  image: ^4.0.17
  in_app_review: ^2.0.6
  intl: ^0.18.0
  package_info_plus: ^4.0.1
  path_provider: ^2.0.15
  provider: ^6.0.5
  rxdart: ^0.27.7
  shared_preferences: ^2.1.1
  state_notifier: ^0.7.2+1
  tutorial_coach_mark: ^1.2.8
  version: ^3.0.2

dev_dependencies:
  build_runner: ^2.3.3
  dependency_validator: ^3.2.2
  freezed: ^2.3.4

dependency_overrides:
  # dependency_validatorを使うときエラーになる
  # https://stackoverflow.com/questions/73561012/flutter-the-method-file-create-has-fewer-named-arguments-than-those-of-overrid
  file: ^6.1.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter: null
