name: flutter_app_components
description: A new Flutter package.
version: 1.0.0
publish_to: none
homepage: "https://github.com/niwatly"

environment:
  sdk: '>=2.16.1 <3.0.0'
  flutter: 2.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # StateNotifierを使って状態管理したい
  # https://pub.dev/packages/state_notifier
  state_notifier: ^0.7.2+1

  # StateNotifierをWidgetTree上で保持したい
  # https://pub.dev/packages/flutter_state_notifier
  flutter_state_notifier: ^0.7.1

  # InheritedWidgetを利用した状態管理を楽に行いたい
  # https://pub.dev/packages/provider
  provider: ^6.0.2

  # RxOperatorを使いたい
  # https://pub.dev/packages/rxdart
  rxdart: ^0.27.3

  # 複雑なRoutingを楽に書きたい
  # https://pub.dev/packages/fluro
  fluro: ^2.0.3

  # URLを外部ブラウザで開きたい
  # https://pub.dev/packages/url_launcher
  url_launcher: ^6.0.20

  # Http通信したい
  # https://pub.dev/packages/http
  http: ^0.13.4

  # Textの文字サイズを自動で調整したい
  # https://pub.dev/packages/auto_size_text
  auto_size_text: ^3.0.0

  # https://pub.dev/packages/in_app_review
  in_app_review: ^2.0.4

  # アプリバージョンとかを取得したい
  # https://pub.dev/packages/package_info#-installing-tab-
  package_info: ^2.0.2

  # 一時ディレクトリを取得するのに使用
  # https://pub.dev/packages/path_provider
  path_provider: ^2.0.9

  # バージョン値を比較したい
  # https://pub.dev/packages/version
  version: ^2.0.0

  # アプリのローカルストレージに値を保存したい
  # https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.0.13

  # 画像からexifを削除したい
  # https://pub.dev/packages/image
  image: ^3.1.1

  # 指定したWidgetにフォーカスするOverlay形式のUI表現を楽に作りたい
  # https://pub.dev/packages/tutorial_coach_mark
  tutorial_coach_mark: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/dart_code_metrics
  dart_code_metrics: ^4.10.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
